name: gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
      working-directory: ask-user
    - run: npm test
      working-directory: ask-user
    - run: npm build
      working-directory: ask-user
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: kevinbader@users.noreply.github.com
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: ask-user/dist/ask-user
